# 1) Importing Required Libraries

In [2]:
import pandas as pd # for data manipulation
import numpy as np  # for data manipulation
from sklearn.preprocessing import LabelEncoder # data preprocessing

In [3]:
df = pd.read_csv("FINAL-SMS-DATA.csv") # Loading the dataset

In [4]:
df.tail()

_protocol   _address         _date  _type  _subject  \
9806          0  AD-AIRTEL  1.730000e+12      1       NaN   
9807          0  JK-UNIONB  1.730000e+12      1       NaN   
9808          0   9.18E+11  1.730000e+12      1       NaN   
9809          0  AD-650022  1.730000e+12      1       NaN   
9810          0  JM-620016  1.730000e+12      1       NaN   

                                                  _body  _toa  _sc_toa  \
9806  Don't miss out on superior indoor coverage wit...   NaN      NaN   
9807  A/c *0485 Credited for Rs:100.00 on 03-11-2024...   NaN      NaN   
9808  Dear Customer, You have a missed call from +91...   NaN      NaN   
9809  Don't miss out on the biggest festive offer. U...   NaN      NaN   
9810  Your Jio no 8356920721 plan has expired. Recha...   NaN      NaN   

      _service_center  _read  _status  _locked  _date_sent  _sub_id  \
9806     9.200000e+11      0       -1        0         0.0      2.0   
9807     9.170000e+11      0       -1        0         0.0      1.0   
9808     9.190000e+13      0       -1        0         0.0      1.0   
9809     9.200000e+11      0       -1        0         0.0      2.0   
9810     9.170000e+11      0       -1        0         0.0      1.0   

            _readable_date _contact_name  
9806  Nov 3, 2024 13:17:10     (Unknown)  
9807  Nov 3, 2024 22:23:07     (Unknown)  
9808  Nov 4, 2024 10:21:09     (Unknown)  
9809  Nov 4, 2024 11:43:38     (Unknown)  
9810  Nov 4, 2024 13:09:27     (Unknown)

In [5]:
df.head(5)

_protocol   _address         _date  _type  _subject  \
0          0  AD-rajpol  1.700000e+12      1       NaN   
1          0  AX-rajpol  1.700000e+12      1       NaN   
2          0   9.19E+11  1.700000e+12      2       NaN   
3          0  AD-AIRDOT  1.720000e+12      1       NaN   
4          0  AX-VBFOOD  1.720000e+12      1       NaN   

                                               _body  _toa  _sc_toa  \
0  Complaint No 279970242301096 registered  at  C...   NaN      NaN   
1  EO has been assigned on your Complaint(not FIR...   NaN      NaN   
2  I am Sankar Rao from Mumbai, and I have an ide...   NaN      NaN   
3  Alert: On receiving any unwanted SMS , please ...   NaN      NaN   
4  CreditChangeCrDayCrLmt Join group to learn abo...   NaN      NaN   

   _service_center  _read  _status  _locked    _date_sent  _sub_id  \
0     9.200000e+11      1       -1        0  1.700000e+12      1.0   
1     9.200000e+11      1       -1        0  1.700000e+12      1.0   
2              NaN      1       -1        0  0.000000e+00      1.0   
3     9.200000e+11      1       -1        0  1.720000e+12      3.0   
4     9.200000e+11      0       -1        0  1.720000e+12      1.0   

     _readable_date _contact_name  
0  17-10-2023 18:34     (Unknown)  
1  18-10-2023 11:54     (Unknown)  
2  29-11-2023 02:55     (Unknown)  
3  01-06-2024 21:51     (Unknown)  
4  04-06-2024 11:57     (Unknown)

In [6]:
df.describe()

_protocol         _date        _type  _subject  _toa  _sc_toa  \
count  9811.000000  9.811000e+03  9811.000000       0.0   0.0      0.0   
mean      0.003567  1.701139e+12     1.038222       NaN   NaN      NaN   
std       0.059624  3.192656e+10     0.208060       NaN   NaN      NaN   
min       0.000000  1.560000e+12     1.000000       NaN   NaN      NaN   
25%       0.000000  1.680000e+12     1.000000       NaN   NaN      NaN   
50%       0.000000  1.710000e+12     1.000000       NaN   NaN      NaN   
75%       0.000000  1.730000e+12     1.000000       NaN   NaN      NaN   
max       1.000000  1.730000e+12     5.000000       NaN   NaN      NaN   

       _service_center        _read      _status  _locked    _date_sent  \
count     7.275000e+03  9811.000000  9811.000000   9811.0  9.811000e+03   
mean      8.324942e+12     0.771889    -0.923147      0.0  1.133819e+12   
std       2.492364e+13     0.419636     0.780500      0.0  8.020633e+11   
min       0.000000e+00     0.000000    -1.000000      0.0  0.000000e+00   
25%       9.170000e+11     1.000000    -1.000000      0.0  0.000000e+00   
50%       9.200000e+11     1.000000    -1.000000      0.0  1.680000e+12   
75%       9.200000e+11     1.000000    -1.000000      0.0  1.730000e+12   
max       9.190000e+13     1.000000    32.000000      0.0  1.730000e+12   

           _sub_id  
count  8158.000000  
mean      0.838563  
std       1.196845  
min      -1.000000  
25%       1.000000  
50%       1.000000  
75%       1.000000  
max       3.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9811 entries, 0 to 9810
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   _protocol        9811 non-null   int64  
 1   _address         9811 non-null   object 
 2   _date            9811 non-null   float64
 3   _type            9811 non-null   int64  
 4   _subject         0 non-null      float64
 5   _body            9810 non-null   object 
 6   _toa             0 non-null      float64
 7   _sc_toa          0 non-null      float64
 8   _service_center  7275 non-null   float64
 9   _read            9811 non-null   int64  
 10  _status          9811 non-null   int64  
 11  _locked          9811 non-null   int64  
 12  _date_sent       9811 non-null   float64
 13  _sub_id          8158 non-null   float64
 14  _readable_date   9811 non-null   object 
 15  _contact_name    9811 non-null   object 
dtypes: float64(7), int64(5), object(4)
memory usage: 1.2+ MB


# 2) define a fucntion that separates the messages as per their category

In [8]:
def categorize_message(body):
    if pd.isna(body):
        return "unknown"
    body_lower = body.lower()
    
    
    if any(keyword in body_lower for keyword in ["bill","plan","A/c""recharge","transaction", "credited", "debited", "balance", "payment", "bank"]):
        return "transaction"
    elif "otp" in body_lower or "one time password" in body_lower:
        return "otp"
    elif any(keyword in body_lower for keyword in ["bonus","join","alert","spam", "win", "offer", "free", "click here","limited","claim","hi"]):
        return "spam"
    elif any(keyword in body_lower for keyword in ["fraud", "scam", "illegal","complaint"]):
        return "fraud"
    elif any(keyword in body_lower for keyword in ["delivered","package", "delivery", "tracking", "courier", "logistic","deliver"]):
        return "logistic"
    else:
        return "personal"
df['category'] = df['_body'].apply(categorize_message) # Creating a new column  names"Category" and apply this function on "_body" column 

# Display the first few rows with the new category column
df[['category', '_body']].head(10)

category                                              _body
0         spam  Complaint No 279970242301096 registered  at  C...
1        fraud  EO has been assigned on your Complaint(not FIR...
2         spam  I am Sankar Rao from Mumbai, and I have an ide...
3         spam  Alert: On receiving any unwanted SMS , please ...
4         spam  CreditChangeCrDayCrLmt Join group to learn abo...
5     logistic  Gold loan now home delivered for Dear Customer...
6     personal  In a meeting, please text/WhatsApp! If urgent,...
7  transaction  This is Sankar Rao Mumbai and we are looking t...
8     personal  Thank you for your interest in AtmosPower’s te...
9         spam  GRT Jewellers Dazzling Diamond Festival, Get U...

In [9]:
df =df[['category', '_body']]

In [10]:
df

category                                              _body
0            spam  Complaint No 279970242301096 registered  at  C...
1           fraud  EO has been assigned on your Complaint(not FIR...
2            spam  I am Sankar Rao from Mumbai, and I have an ide...
3            spam  Alert: On receiving any unwanted SMS , please ...
4            spam  CreditChangeCrDayCrLmt Join group to learn abo...
...           ...                                                ...
9806         spam  Don't miss out on superior indoor coverage wit...
9807  transaction  A/c *0485 Credited for Rs:100.00 on 03-11-2024...
9808     personal  Dear Customer, You have a missed call from +91...
9809  transaction  Don't miss out on the biggest festive offer. U...
9810  transaction  Your Jio no 8356920721 plan has expired. Recha...

[9811 rows x 2 columns]

## 2) Data Preprocessing

In [11]:
encoder = LabelEncoder()

In [12]:
df["category"] =encoder.fit_transform(df["category"])

In [13]:
df

category                                              _body
0            4  Complaint No 279970242301096 registered  at  C...
1            0  EO has been assigned on your Complaint(not FIR...
2            4  I am Sankar Rao from Mumbai, and I have an ide...
3            4  Alert: On receiving any unwanted SMS , please ...
4            4  CreditChangeCrDayCrLmt Join group to learn abo...
...        ...                                                ...
9806         4  Don't miss out on superior indoor coverage wit...
9807         5  A/c *0485 Credited for Rs:100.00 on 03-11-2024...
9808         3  Dear Customer, You have a missed call from +91...
9809         5  Don't miss out on the biggest festive offer. U...
9810         5  Your Jio no 8356920721 plan has expired. Recha...

[9811 rows x 2 columns]

In [14]:
df.dropna(inplace =True)

In [15]:
#label_mapping = dict(zip(encoder.classes_, range(len(encoder.classes_))))

In [16]:
#print("Label Mapping:", label_mapping)


# 3)Splitting the data into training and testing

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
x = vectorizer.fit_transform(df["_body"])

In [18]:
y = df["category"]

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.2,random_state =42)

# 4) model building

In [21]:
from sklearn.naive_bayes import MultinomialNB

In [22]:
# Train a Naive Bayes Classifier
model = MultinomialNB(alpha=0.3)
model.fit(x_train, y_train)

MultinomialNB(alpha=0.3)

## a) model evaluation

In [29]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
# Evaluate the model
y_pred = model.predict(x_test)
print(classification_report(y_test, y_pred))
print(accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.30      0.75      0.43        12
           1       0.31      0.73      0.43        11
           2       0.55      0.95      0.70        62
           3       0.98      0.77      0.86       819
           4       0.75      0.93      0.83       471
           5       0.94      0.92      0.93       587

    accuracy                           0.86      1962
   macro avg       0.64      0.84      0.70      1962
weighted avg       0.89      0.86      0.87      1962

0.8588175331294597
[[  9   0   2   0   0   1]
 [  0   8   0   0   2   1]
 [  0   0  59   1   0   2]
 [ 15  10  36 630 107  21]
 [  6   7   7   7 437   7]
 [  0   1   3   8  33 542]]


In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
lr_model = LogisticRegression() 

In [26]:
lr_model.fit(x_train,y_train)

LogisticRegression()

In [28]:
# tessting accuracy

In [29]:
predict = lr_model.predict(x_test)

In [30]:
accuracy_score(y_test,predict)

0.9658511722731906

In [31]:
# traning accuracy

In [32]:
train_pred = lr_model.predict(x_train)

In [33]:
accuracy_score(y_train,train_pred)

0.9994903160040775

## 5) Pickling the model 

In [34]:
import pickle 

In [35]:
with open("model1.pkl","wb") as file:
    pickle.dump(lr_model,file)
    print("sucessfully created pickle file")

sucessfully created pickle file


In [36]:
with open("naive.pkl","wb") as file:
    pickle.dump(model,file)
    print("sucessfully created pickle file")

sucessfully created pickle file


In [37]:
new_message = ["Your power bill of $100 is due. Pay now to avoid penalties."]
new_message_vectorized = vectorizer.transform(new_message)
prediction = lr_model.predict(new_message_vectorized)
print("Predicted Category:", prediction[0])

Predicted Category: 5


In [38]:
with open("vectorizer1.pkl","wb") as file:
    pickle.dump(vectorizer,file)
    print("sucessfully created pickle file")

sucessfully created pickle file


## Method 2: Using Classification Algorithm K-means

In [39]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(df['_body'])


num_clusters = 6 # we have 6 categories hence here we define 6 clusters
kmeans = KMeans(n_clusters=num_clusters, random_state=42)
df['cluster'] = kmeans.fit_predict(X) # creating the new column that stores the categorical clusters

# Step 3: Analyze clusters
print(df)


      category                                              _body  cluster
0            4  Complaint No 279970242301096 registered  at  C...        3
1            0  EO has been assigned on your Complaint(not FIR...        3
2            4  I am Sankar Rao from Mumbai, and I have an ide...        3
3            4  Alert: On receiving any unwanted SMS , please ...        3
4            4  CreditChangeCrDayCrLmt Join group to learn abo...        3
...        ...                                                ...      ...
9806         4  Don't miss out on superior indoor coverage wit...        0
9807         5  A/c *0485 Credited for Rs:100.00 on 03-11-2024...        5
9808         3  Dear Customer, You have a missed call from +91...        5
9809         5  Don't miss out on the biggest festive offer. U...        3
9810         5  Your Jio no 8356920721 plan has expired. Recha...        0

[9810 rows x 3 columns]


In [165]:
df

category  \
0           Promotions/Offers   
1           Promotions/Offers   
2           Promotions/Offers   
3           Promotions/Offers   
4           Promotions/Offers   
...                       ...   
9806    General Notifications   
9807  Banking/Account Updates   
9808  Banking/Account Updates   
9809        Promotions/Offers   
9810    General Notifications   

                                                  _body  cluster  
0     Complaint No 279970242301096 registered  at  C...        3  
1     EO has been assigned on your Complaint(not FIR...        3  
2     I am Sankar Rao from Mumbai, and I have an ide...        3  
3     Alert: On receiving any unwanted SMS , please ...        3  
4     CreditChangeCrDayCrLmt Join group to learn abo...        3  
...                                                 ...      ...  
9806  Don't miss out on superior indoor coverage wit...        0  
9807  A/c *0485 Credited for Rs:100.00 on 03-11-2024...        5  
9808  Dear Customer, You have a missed call from +91...        5  
9809  Don't miss out on the biggest festive offer. U...        3  
9810  Your Jio no 8356920721 plan has expired. Recha...        0  

[9810 rows x 3 columns]

In [40]:
df

category                                              _body  cluster
0            4  Complaint No 279970242301096 registered  at  C...        3
1            0  EO has been assigned on your Complaint(not FIR...        3
2            4  I am Sankar Rao from Mumbai, and I have an ide...        3
3            4  Alert: On receiving any unwanted SMS , please ...        3
4            4  CreditChangeCrDayCrLmt Join group to learn abo...        3
...        ...                                                ...      ...
9806         4  Don't miss out on superior indoor coverage wit...        0
9807         5  A/c *0485 Credited for Rs:100.00 on 03-11-2024...        5
9808         3  Dear Customer, You have a missed call from +91...        5
9809         5  Don't miss out on the biggest festive offer. U...        3
9810         5  Your Jio no 8356920721 plan has expired. Recha...        0

[9810 rows x 3 columns]

## 2) Data Preprocessing

In [42]:
new_df =df[['_body',"cluster"]]

In [43]:
x1 = new_df["_body"]
y1 = new_df["cluster"]

In [56]:
vectorizer = CountVectorizer()

In [57]:
x1 = vectorizer.fit_transform(x1)

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
x_train,x_test,y_train,y_test = train_test_split(x1,y1,test_size =0.2,random_state =42)

## 3) Model Building

In [60]:
from sklearn.naive_bayes import MultinomialNB

In [62]:
final_model = MultinomialNB()

In [63]:
final_model.fit(x_train,y_train)

MultinomialNB()

In [64]:
final_model_pred = final_model.predict(x_test)

In [65]:
accuracy_score(y_test,final_model_pred)

0.9347604485219164

In [66]:
from sklearn.linear_model import LogisticRegression

In [69]:
lr_model = LogisticRegression()

In [70]:
lr_model.fit(x_train,y_train)

LogisticRegression()

In [71]:
lr_pred = lr_model.predict(x_test)

In [72]:
accuracy_score(y_test,lr_pred)

0.9928644240570846

In [74]:
lr_train = lr_model.predict(x_train)

In [79]:
accuracy_score(y_train,lr_train)

1.0

## 3) Pickeling model

In [77]:
import pickle 
with open("last_model.pkl","wb") as file:
    pickle.dump(lr_model,file)
    print("Pickle File Created Successfully")

Pickle File Created Successfully


In [94]:
df["_body"][9807]

'A/c *0485 Credited for Rs:100.00 on 03-11-2024 22:22:58 by Mob Bk ref no 430816991834 Avl Bal Rs:919.05.Never Share OTP/PIN/CVV-Union Bank of India'

In [100]:
df[40:80]

category                                              _body  cluster
40         4  While receiving any international call, if an ...        3
41         3  Dear Mr Shankar, Your appointment at Tathaapi ...        3
42         5  Dear Customer, Thank you for your visit @ Tath...        3
43         5  Dear customer, 41 Loyalty points added to your...        3
44         3  Airtel WiFi కాలింగ్తో మెరుగైన ఇండోర్ కవరేజీని ...        3
45         4  Don't miss out on superior indoor coverage wit...        0
46         5  UBER INDIA SYSTEMS PRIVATE LIMITED has request...        3
47         3  Rs.5000  Uber E-Gift Voucher purchased via Pho...        3
48         3  You've received Rs.150 cashback from PhonePe a...        3
49         3  It is to inform you that an unexpected Power o...        3
50         3  It is to inform you that an unexpected Power o...        3
51         5  Get mode-wise analysis of your collections wit...        3
52         4  Dear YESKART PRIVATE LIMITED, AAXXXXXX0K,\nInc...        3
53         5  Need a safety net for your business capital? S...        3
54         5  Dear Poonawalla Customer,\nEMI amount of 39023...        3
55         3  True love never dies! Enter the shadows with T...        3
56         3  SBIUPI i5E%2BGGSIJy4g9z4l4LPHuxdPMOK67p4eHywnb...        3
57         3  JP7 E965*ED59R88442Y*o*1YbU***T4gKfEZ*H*6**jTb...        3
58         3  HDFCUPI 7mU8wQHN4ZSsZV7i9Ns9F1FXXewawsfC4yUQq3...        3
59         3           JP7 *TZ4#4$I*!*N*6j!B#k*R$IKVh*$206&$!e!        3
60         5  Google Pay registration is initiated for ICICI...        2
61         5  UPI registration on Google Pay has started. Do...        2
62         4  We regret power outage in your premise due to ...        3
63         5  Dear Sankar Rao Vysyaraju your Navi Cash loan ...        3
64         3  Digi Dakiya WhatsApp CRM\nManage Reminders, No...        3
65         5  Dear UPI user A/C X8641 debited by 500.0 on da...        4
66         3  Dear Customer, You have entered incorrect MPIN...        3
67         5  Rs.55 paid at Bellupada for 24BH4887A on 31-08...        5
68         5  Rs.115 paid at Bellupada for 24BH4887A on 31-0...        5
69         5  Dear Applicant, Your request for ROR1B CERTIFI...        3
70         5  Dear Applicant, Your request for ROR1B CERTIFI...        3
71         4  The person you were calling is now available t...        0
72         5  Dear Applicant, Your request for ROR1B CERTIFI...        3
73         5  Dear Applicant, Your request for ROR1B CERTIFI...        3
74         4  Experience The Luxury Of Shirts Crafted From R...        3
75         5  Your AC XXXXX454848 Debited INR 590.00 on 31/0...        5
76         5  Your ZIP bill of Rs.29610 is generated. Settle...        3
77         5  Avl Bal for A/c XXXX0004 as on 01-SEP-2024 05:...        5
78         5  Important reminder: Your plan includes access ...        1
79         4  Hi Sankar, Get up to 10% off* on trendy jewell...        3